version: 2.1

jobs:
  build-linux-amd64:
    docker:
      - image: circleci/gcc:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y qt5-default build-essential
      - run:
          name: Build Project
          command: |
            qmake
            make
      - run:
          name: Run Tests
          command: make test

  build-linux-arm64:
    machine:
      image: arm64v8/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt update
            apt install -y qt5-default build-essential
      - run:
          name: Build Project
          command: |
            qmake
            make
      - run:
          name: Run Tests
          command: make test

  build-windows-amd64:
    machine:
      image: windows-server-2019
    steps:
      - checkout
      - run:
          name: Install Qt
          command: |
            choco install qt5 -y
            set PATH=C:\Qt\5.x.x\msvc2019_64\bin;%PATH%
      - run:
          name: Build Project
          command: |
            qmake
            nmake
      - run:
          name: Run Tests
          command: nmake test

  build-macos-arm64:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            brew install qt
            export PATH="/usr/local/opt/qt/bin:$PATH"
      - run:
          name: Build Project
          command: |
            qmake
            make
      - run:
          name: Run Tests
          command: make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-linux-amd64
      - build-linux-arm64
      - build-windows-amd64
      - build-macos-arm64

