# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pedro/Projects/SB_MMO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pedro/Projects/SB_MMO/sb_rpg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pedro/Projects/SB_MMO/sb_rpg/CMakeFiles /Users/pedro/Projects/SB_MMO/sb_rpg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pedro/Projects/SB_MMO/sb_rpg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named valkyrie

# Build rule for target.
valkyrie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 valkyrie
.PHONY : valkyrie

# fast build rule for target.
valkyrie/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/build
.PHONY : valkyrie/fast

game_utils.o: game_utils.cpp.o
.PHONY : game_utils.o

# target to build an object file
game_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/game_utils.cpp.o
.PHONY : game_utils.cpp.o

game_utils.i: game_utils.cpp.i
.PHONY : game_utils.i

# target to preprocess a source file
game_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/game_utils.cpp.i
.PHONY : game_utils.cpp.i

game_utils.s: game_utils.cpp.s
.PHONY : game_utils.s

# target to generate assembly for a file
game_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/game_utils.cpp.s
.PHONY : game_utils.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/main.cpp.s
.PHONY : main.cpp.s

src/ai.o: src/ai.cpp.o
.PHONY : src/ai.o

# target to build an object file
src/ai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/ai.cpp.o
.PHONY : src/ai.cpp.o

src/ai.i: src/ai.cpp.i
.PHONY : src/ai.i

# target to preprocess a source file
src/ai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/ai.cpp.i
.PHONY : src/ai.cpp.i

src/ai.s: src/ai.cpp.s
.PHONY : src/ai.s

# target to generate assembly for a file
src/ai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/ai.cpp.s
.PHONY : src/ai.cpp.s

src/api.o: src/api.cpp.o
.PHONY : src/api.o

# target to build an object file
src/api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/api.cpp.o
.PHONY : src/api.cpp.o

src/api.i: src/api.cpp.i
.PHONY : src/api.i

# target to preprocess a source file
src/api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/api.cpp.i
.PHONY : src/api.cpp.i

src/api.s: src/api.cpp.s
.PHONY : src/api.s

# target to generate assembly for a file
src/api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/api.cpp.s
.PHONY : src/api.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/commands.o: src/commands.cpp.o
.PHONY : src/commands.o

# target to build an object file
src/commands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/commands.cpp.o
.PHONY : src/commands.cpp.o

src/commands.i: src/commands.cpp.i
.PHONY : src/commands.i

# target to preprocess a source file
src/commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/commands.cpp.i
.PHONY : src/commands.cpp.i

src/commands.s: src/commands.cpp.s
.PHONY : src/commands.s

# target to generate assembly for a file
src/commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/commands.cpp.s
.PHONY : src/commands.cpp.s

src/credits.o: src/credits.cpp.o
.PHONY : src/credits.o

# target to build an object file
src/credits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/credits.cpp.o
.PHONY : src/credits.cpp.o

src/credits.i: src/credits.cpp.i
.PHONY : src/credits.i

# target to preprocess a source file
src/credits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/credits.cpp.i
.PHONY : src/credits.cpp.i

src/credits.s: src/credits.cpp.s
.PHONY : src/credits.s

# target to generate assembly for a file
src/credits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/credits.cpp.s
.PHONY : src/credits.cpp.s

src/gamepad.o: src/gamepad.cpp.o
.PHONY : src/gamepad.o

# target to build an object file
src/gamepad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/gamepad.cpp.o
.PHONY : src/gamepad.cpp.o

src/gamepad.i: src/gamepad.cpp.i
.PHONY : src/gamepad.i

# target to preprocess a source file
src/gamepad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/gamepad.cpp.i
.PHONY : src/gamepad.cpp.i

src/gamepad.s: src/gamepad.cpp.s
.PHONY : src/gamepad.s

# target to generate assembly for a file
src/gamepad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/src/gamepad.cpp.s
.PHONY : src/gamepad.cpp.s

srv/serverRegistration.o: srv/serverRegistration.cpp.o
.PHONY : srv/serverRegistration.o

# target to build an object file
srv/serverRegistration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/srv/serverRegistration.cpp.o
.PHONY : srv/serverRegistration.cpp.o

srv/serverRegistration.i: srv/serverRegistration.cpp.i
.PHONY : srv/serverRegistration.i

# target to preprocess a source file
srv/serverRegistration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/srv/serverRegistration.cpp.i
.PHONY : srv/serverRegistration.cpp.i

srv/serverRegistration.s: srv/serverRegistration.cpp.s
.PHONY : srv/serverRegistration.s

# target to generate assembly for a file
srv/serverRegistration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valkyrie.dir/build.make CMakeFiles/valkyrie.dir/srv/serverRegistration.cpp.s
.PHONY : srv/serverRegistration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... valkyrie"
	@echo "... game_utils.o"
	@echo "... game_utils.i"
	@echo "... game_utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ai.o"
	@echo "... src/ai.i"
	@echo "... src/ai.s"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/commands.o"
	@echo "... src/commands.i"
	@echo "... src/commands.s"
	@echo "... src/credits.o"
	@echo "... src/credits.i"
	@echo "... src/credits.s"
	@echo "... src/gamepad.o"
	@echo "... src/gamepad.i"
	@echo "... src/gamepad.s"
	@echo "... srv/serverRegistration.o"
	@echo "... srv/serverRegistration.i"
	@echo "... srv/serverRegistration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

