#############################################################################
# Makefile for building: untitled
# Generated by qmake (3.1) (Qt 6.7.3)
# Project:  untitled.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile untitled.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = 
CFLAGS        = -pipe -fobjc-arc -fobjc-arc -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -fobjc-arc -fobjc-arc -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -I/opt/homebrew/share/qt/mkspecs/macx-clang
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = untitled1.0.0
DISTDIR = /Users/pedro/Projects/SB_MMO/sb_rpg/.tmp/untitled1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -fobjc-arc -fobjc-arc -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -L/opt/homebrew/lib -lSDL2 -lSDL2_image -framework OpenGL -framework Metal -framework QuartzCore   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/ai.cpp \
		src/camera.cpp \
		src/gamepad.cpp \
		main.cpp 
OBJECTS       = ai.o \
		camera.o \
		gamepad.o \
		main.o
DIST          = Makefile \
		MetalRenderer.m \
		/opt/homebrew/share/qt/mkspecs/features/spec_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/clang-mac.conf \
		/opt/homebrew/share/qt/mkspecs/qconfig.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpcquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/opt/homebrew/share/qt/mkspecs/features/qt_functions.prf \
		/opt/homebrew/share/qt/mkspecs/features/qt_config.prf \
		/opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/share/qt/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/share/qt/mkspecs/features/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/resolve_config.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/mac.prf \
		/opt/homebrew/share/qt/mkspecs/features/warn_on.prf \
		/opt/homebrew/share/qt/mkspecs/features/qmake_use.prf \
		/opt/homebrew/share/qt/mkspecs/features/file_copies.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/rez.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/share/qt/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/share/qt/mkspecs/features/exceptions.prf \
		/opt/homebrew/share/qt/mkspecs/features/yacc.prf \
		/opt/homebrew/share/qt/mkspecs/features/lex.prf \
		untitled.pro src/ai.h \
		update src/ai.cpp \
		src/camera.cpp \
		src/gamepad.cpp \
		main.cpp
QMAKE_TARGET  = untitled
DESTDIR       = 
TARGET        = untitled

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.2
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/pedro/Projects/SB_MMO/sb_rpg/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/pedro/Projects/SB_MMO/sb_rpg/untitled.pro


include /opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

untitled:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: untitled.pro /opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf /opt/homebrew/share/qt/mkspecs/features/spec_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/clang-mac.conf \
		/opt/homebrew/share/qt/mkspecs/qconfig.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpcquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/opt/homebrew/share/qt/mkspecs/features/qt_functions.prf \
		/opt/homebrew/share/qt/mkspecs/features/qt_config.prf \
		/opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/share/qt/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/share/qt/mkspecs/features/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/resolve_config.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/mac.prf \
		/opt/homebrew/share/qt/mkspecs/features/warn_on.prf \
		/opt/homebrew/share/qt/mkspecs/features/qmake_use.prf \
		/opt/homebrew/share/qt/mkspecs/features/file_copies.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/rez.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/share/qt/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/share/qt/mkspecs/features/exceptions.prf \
		/opt/homebrew/share/qt/mkspecs/features/yacc.prf \
		/opt/homebrew/share/qt/mkspecs/features/lex.prf \
		untitled.pro
	$(QMAKE) -o Makefile untitled.pro
/opt/homebrew/share/qt/mkspecs/features/spec_pre.prf:
/opt/homebrew/share/qt/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt/6.7.3/share/qt/mkspecs/common/clang-mac.conf:
/opt/homebrew/share/qt/mkspecs/qconfig.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpcquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpcquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlbuiltins.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/opt/homebrew/share/qt/mkspecs/features/qt_functions.prf:
/opt/homebrew/share/qt/mkspecs/features/qt_config.prf:
/opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/share/qt/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/sdk.prf:
/opt/homebrew/share/qt/mkspecs/features/toolchain.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/share/qt/mkspecs/features/default_pre.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/share/qt/mkspecs/features/resolve_config.prf:
/opt/homebrew/share/qt/mkspecs/features/default_post.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/default_post.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/mac.prf:
/opt/homebrew/share/qt/mkspecs/features/warn_on.prf:
/opt/homebrew/share/qt/mkspecs/features/qmake_use.prf:
/opt/homebrew/share/qt/mkspecs/features/file_copies.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/rez.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/share/qt/mkspecs/features/testcase_targets.prf:
/opt/homebrew/share/qt/mkspecs/features/exceptions.prf:
/opt/homebrew/share/qt/mkspecs/features/yacc.prf:
/opt/homebrew/share/qt/mkspecs/features/lex.prf:
untitled.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile untitled.pro

qmake_all: FORCE


all: Makefile untitled

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

ai.o: src/ai.cpp src/AI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ai.o src/ai.cpp

camera.o: src/camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o src/camera.cpp

gamepad.o: src/gamepad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamepad.o src/gamepad.cpp

main.o: main.cpp /opt/homebrew/include/SDL2/SDL.h \
		/opt/homebrew/include/SDL2/SDL_main.h \
		/opt/homebrew/include/SDL2/SDL_stdinc.h \
		/opt/homebrew/include/SDL2/SDL_config.h \
		/opt/homebrew/include/SDL2/SDL_platform.h \
		/opt/homebrew/include/SDL2/begin_code.h \
		/opt/homebrew/include/SDL2/close_code.h \
		/opt/homebrew/include/SDL2/SDL_assert.h \
		/opt/homebrew/include/SDL2/SDL_atomic.h \
		/opt/homebrew/include/SDL2/SDL_audio.h \
		/opt/homebrew/include/SDL2/SDL_error.h \
		/opt/homebrew/include/SDL2/SDL_endian.h \
		/opt/homebrew/include/SDL2/SDL_mutex.h \
		/opt/homebrew/include/SDL2/SDL_thread.h \
		/opt/homebrew/include/SDL2/SDL_rwops.h \
		/opt/homebrew/include/SDL2/SDL_clipboard.h \
		/opt/homebrew/include/SDL2/SDL_cpuinfo.h \
		/opt/homebrew/include/SDL2/SDL_events.h \
		/opt/homebrew/include/SDL2/SDL_video.h \
		/opt/homebrew/include/SDL2/SDL_pixels.h \
		/opt/homebrew/include/SDL2/SDL_rect.h \
		/opt/homebrew/include/SDL2/SDL_surface.h \
		/opt/homebrew/include/SDL2/SDL_blendmode.h \
		/opt/homebrew/include/SDL2/SDL_keyboard.h \
		/opt/homebrew/include/SDL2/SDL_keycode.h \
		/opt/homebrew/include/SDL2/SDL_scancode.h \
		/opt/homebrew/include/SDL2/SDL_mouse.h \
		/opt/homebrew/include/SDL2/SDL_joystick.h \
		/opt/homebrew/include/SDL2/SDL_guid.h \
		/opt/homebrew/include/SDL2/SDL_gamecontroller.h \
		/opt/homebrew/include/SDL2/SDL_sensor.h \
		/opt/homebrew/include/SDL2/SDL_quit.h \
		/opt/homebrew/include/SDL2/SDL_gesture.h \
		/opt/homebrew/include/SDL2/SDL_touch.h \
		/opt/homebrew/include/SDL2/SDL_filesystem.h \
		/opt/homebrew/include/SDL2/SDL_haptic.h \
		/opt/homebrew/include/SDL2/SDL_hidapi.h \
		/opt/homebrew/include/SDL2/SDL_hints.h \
		/opt/homebrew/include/SDL2/SDL_loadso.h \
		/opt/homebrew/include/SDL2/SDL_log.h \
		/opt/homebrew/include/SDL2/SDL_messagebox.h \
		/opt/homebrew/include/SDL2/SDL_metal.h \
		/opt/homebrew/include/SDL2/SDL_power.h \
		/opt/homebrew/include/SDL2/SDL_render.h \
		/opt/homebrew/include/SDL2/SDL_shape.h \
		/opt/homebrew/include/SDL2/SDL_system.h \
		/opt/homebrew/include/SDL2/SDL_timer.h \
		/opt/homebrew/include/SDL2/SDL_version.h \
		/opt/homebrew/include/SDL2/SDL_locale.h \
		/opt/homebrew/include/SDL2/SDL_misc.h \
		/opt/homebrew/include/SDL2/SDL_image.h \
		Samurai_Babel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

